services:
  go-app:
    image: docker.io/fajargst/url_shortener:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:14-alpine 
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
  
  ngrok:
    image: ngrok/ngrok
    ports:
      - "4040:4040"
    networks:
      - app-network
    env_file:
      - .env
    command: http go-app:8080
    depends_on:
      - go-app

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
